### ISSUE TITLE
Node.js v5.1.1 not supported?

### ISSUE THREAD

**Issue by silverbucket** [contra/rtc-everywhere#10]
Trying this module out, it appears I can't get past initialization:

``` javascript
var rtc = require('rtc-everywhere')();

if (rtc.supported === false) {
  console.error(rtc.platform + ' platform not supported!');
  process.exit(1);
}

console.log(rtc);

var pc = new rtc.RTCPeerConnection();
pc.createOffer(function (offer) {
  console.log("offer: ", offer);
});
```

```
$ node service.js
node platform not supported!
```

If I skip the check, and do a `console.log` on the `rtc` object:

```
{ platform: 'node',
  supported: false,
  getUserMedia: [Function],
  RTCPeerConnection: undefined,
  RTCSessionDescription: undefined,
  RTCIceCandidate: undefined,
  attachStream: [Function] }
```

Am I doing something wrong here? Right now I'm just trying to generate an offer, nothing else. No signalling or anything. 

```
$ node -v 
v5.1.1
```

**Comment by RangerMauve** [comment]
Did you do a `npm install wrtc` and ensure that that's all set up?

**Comment by yocontra** [comment]
Install the `wrtc` module.

I'll leave this open as a reminder that I need to create more detailed docs for each platform.
