### ISSUE TITLE
Camera switching

### ISSUE THREAD

**Issue by openGeeksLab** [contra/rtc-everywhere#12]
Does this module support Camera switching (back, front modes)?
If yes, could you show example?
For React-Native

**Comment by RangerMauve** [comment]
The easiest way to do it is to use `MediaStreamTrack.getSources` to get a list of video sources you could use. Then create a new `PeerConnection` with the `MediaStream` from `getUserMedia` specifying the `video` property to be the video source you want.

**Comment by yocontra** [comment]
That ^
